development: &database
  adapter: mysql2
  database: atut_development
  username: atut
  password:
  encoding: UTF8
  collation: utf8_polish_ci
  # host: "localhost"
  # port: 3306
  pool: 5

test:
  <<: *database
  database: atut_test

production:
  <<: *database
  database: atut_production

staging:
  <<: *database
  database: atut_staging

